### ISSUE TITLE
SWC website ready to setup!

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/2016-04-25-utoronto#1]
Hey @mbonsma who were the instructors again for the workshops? 

Any other details I should I know about for the workshops?

**Comment by lwjohnst86** [comment]
I need to know the dates and workshop topic. From what I've written down (please confirm):
- Apr 25-26, 2016 - R
- May 9-10, 2016 - Python
- May 26-27 - ?

I need the address where the event is taking place. For each workshop.

Is Dawn or you (@mbonsma) the organizer/contact?

I'll have more questions later, but this is good so far :smile:

**Comment by lwjohnst86** [comment]
What are the last names of:
- Emily
- Justin
- Dano

**Comment by mbonsma** [comment]
@lwjohnst86, it should all in the spreadsheet I emailed around (not pasting here, but I'll email you again). The third is May 26-27, yes. I don't know the helper's last names except Dano Morrison. 

I can be the contact person, but it might be good to have both Dawn and I as contacts if possible?

**Comment by lwjohnst86** [comment]
Thanks @mbonsma. I had been using that spreadsheet, but it doesn't have all the info (like last names). Just saw the address right now, haha sorry about that!

The last workshop topic hasn't been decided yet? 

Only one person can be a contact person. So I'll put you.

**Comment by mbonsma** [comment]
The third one is Git/bash/R. I'll see if I can track down helper last names!

**Comment by linamnt** [comment]
Emily Kramer, Dano Morrison, Justin Kenney!

On Tue, Mar 15, 2016 at 12:07 PM, Madeleine Bonsma <notifications@github.com

> wrote:
> 
> The third one is Git/bash/R. I'll see if I can track down helper last
> names!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/UofTCoders/2016-04-25-utoronto/issues/1#issuecomment-196899562

## 

Lina Tran
MSc. Candidate | Frankland Lab http://www.franklandlab.com/
Department of Physiology
University of Toronto

**Comment by mbonsma** [comment]
Sweet, @linamnt saving the day as usual :smile: :clap:

**Comment by lwjohnst86** [comment]
They are now live!! (Still need eventbrite number, but that is not a big deal)
- http://uoftcoders.github.io/2016-04-25-utoronto/
- http://uoftcoders.github.io/2016-05-09-utoronto/
- http://uoftcoders.github.io/2016-05-26-utoronto/

:smile:

**Comment by linamnt** [comment]
Good job Luke, looks great!

There is just a tiny typo for the date on the May 9-10th workshop page. It
says May 5-9 instead of 9-10.

Thanks again :)

On Tue, Mar 15, 2016 at 4:02 PM, Luke W Johnston notifications@github.com
wrote:

> They are now live!! (Still need eventbrite number, but that is not a big
> deal)
> - http://uoftcoders.github.io/2016-04-25-utoronto/
> - http://uoftcoders.github.io/2016-05-09-utoronto/
> - http://uoftcoders.github.io/2016-05-26-utoronto/
> 
> [image: :smile:]
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/2016-04-25-utoronto/issues/1#issuecomment-196998673

## 

Lina Tran
MSc. Candidate | Frankland Lab http://www.franklandlab.com/
Department of Physiology
University of Toronto

**Comment by lwjohnst86** [comment]
Thanks for catching that! Fixed :)

**Comment by lwjohnst86** [comment]
Hey everyone, will we be using an etherpad? I could include it into the website, as it is an option..

Otherwise, the websites are all done! Have the eventbrite up and everything! :D

**Comment by mbonsma** [comment]
I think it's a good idea to use an etherpad, yeah. Want to set one up for each event?

**Comment by lwjohnst86** [comment]
Yea, I can set one up :)
