### ISSUE TITLE
Add links between events to all websites

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/2016-04-25-utoronto#3]
I think it would be handy if there was a little section on each of these three websites that linked to the other future events, something like:

"Can't make it to this event? Check out our other upcoming workshops: May 9-10 and May 26-27 (for people identifying as female)."

I could make that section, I'm just not sure where the best place is to put it. Thoughts?

**Comment by lwjohnst86** [comment]
That would be useful. How about right below 'Contact' as a 'Note:' header or something?

**Comment by mbonsma** [comment]
Sure, sounds good.
