### ISSUE TITLE
Change R lesson to "R for Reproducible Scientific Analysis"

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/2016-04-25-utoronto#8]
We decided in our instructor chat on Monday to use the [R for reproducible scientific analysis](http://swcarpentry.github.io/r-novice-gapminder/) lesson instead of the programming in R lesson that's on the website. Perhaps we should update the website to reflect this?

**Comment by QuLogic** [comment]
So I guess we can close this one, then?
